description: Karma Alertmanager UI
query: http_headval:www-authenticate.lk:"karma alertmanager ui"
tags:
- proto:http
- product:karma-alertmanager
- type:supervision
- vendor:karma
version: 20260916T000000Z
