description: OpenSearch Security
query: http_headval:www-authenticate.lk:"opensearch security"
tags:
- proto:http
- product:opensearch-security
- type:database
- vendor:opensearch
version: 20260916T000000Z
